version: "3.7"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ferretdb

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:latest
    container_name: ferretdb
    restart: on-failure
    environment:
      FERRETDB_POSTGRESQL_URL: postgres://user:password@postgres:5432/ferretdb?pool_max_conns=20
      FERRETDB_TELEMETRY: disable
      FERRETDB_LOG_LEVEL: error
    depends_on:
      - postgres

  connector:
    container_name: connector
    image: ghcr.io/nmshd/connector:latest
    environment:
      CUSTOM_CONFIG_LOCATION: "/config.json"
    volumes:
      - ./config.json:/config.json:ro
    ports:
      - 8080:80
    depends_on:
      - ferretdb

networks:
  default:
    name: ferret_connector_network
